site_name: "nextjs-medpoint-batch-55"
site_description: "NextJS medpoint Pre IP batch 55"

plugins:
  - techdocs-core
nav:
  - Getting Started: index.md
  - Convention : convention.md
  - How To Run : how-to-run.md