name: Medpoint App Deployment

on:
  push:
    tags:
      - "v*" # Menjalankan pipelane ketika previx dari push tagnya 'v' (example: v1.0.1)

jobs:
  deploy:
    name: Build and Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Setup Gitea token for dependencies
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_ACCESS_TOKEN }}
        run: |
          git config --global url."https://$GITEA_TOKEN@gitea.sev-2.com".insteadOf ssh://gitea.sev-2.com

      - name: Install dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Install vercel CLI
        run: yarn install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: vercel --prod --yes --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID
